export const RouteName =  {
    START_SCREEN:'StartScreen',
    CREATE_ACCOUNT_SCREEN:'createAccountScreen',
    LOGIN_SCREEN:'loginScreen',
    PASSWORD_SCREEN:'passwordScreen',
    PASSWORD_TYPING_SCREEN:'PasswordTypingScreen',
    WRONG_PASSWORD_SCREEN:'WrongPasswordScreen',
    PASSWORD_RECOVERY_SCREEN:'PasswordRecoveryScreen',
    PASSWORD_RECOVERY_CODE_SCREEN:'PasswordRecoveryCodeScreen',
    NEW_PASSWORD_SCREEN:'NewPasswordScreen',
    MAXIMUM_ATTEMPTS_SCREEN:'MaximumAttemptsScreen',
    HELLO_CARD_SCREEN:'HelloCardScreen',
    READY_CARD_SCREEN:'ReadyCardScreen',
    PROFILE_SCREEN:'ProfileScreen',
    FULL_PROFILE_SCREEN:'FullProfileScreen',
    SHOP_SCREEN:'Shop-Screen',
}