export const RouteName = {
  START_SCREEN: 'StartScreen',
  CREATE_ACCOUNT_SCREEN: 'createAccountScreen',
  LOGIN_SCREEN: 'loginScreen',
  PASSWORD_SCREEN: 'passwordScreen',
  PASSWORD_TYPING_SCREEN: 'PasswordTypingScreen',
  WRONG_PASSWORD_SCREEN: 'WrongPasswordScreen',
  PASSWORD_RECOVERY_SCREEN: 'PasswordRecoveryScreen',
  PASSWORD_RECOVERY_CODE_SCREEN: 'PasswordRecoveryCodeScreen',
  NEW_PASSWORD_SCREEN: 'NewPasswordScreen',
  MAXIMUM_ATTEMPTS_SCREEN: 'MaximumAttemptsScreen',
  HELLO_CARD_SCREEN: 'HelloCardScreen',
  READY_CARD_SCREEN: 'ReadyCardScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  FULL_PROFILE_SCREEN: 'FullProfileScreen',
  SHOP_SCREEN: 'Shop-Screen',
  FLASH_SALE_LIVE_SCREEN: 'Flash_Sale_Live_Screen',
  FLASH_SALE_SCREEN: 'Flash_Sale_Screen',
  FLASH_SALE_FULL_SCREEN: 'Flash_Sale_Full_Screen',
  LIVE_SCREEN: 'Live_Screen',
  STORY_DOTS_SCREEN: 'Story_Dots_Screen',
  STORY_DOTS_TAB_SCREEN: 'Story_Dots_Tab_Screen',
  STORY_PRODUCT_STYLE01_SCREEN: 'Story_Product_Style01_Screen',
  STORY_BANNER_SCREEN: 'Story_Banner_Screen',
  STORY_PRODUCT_STYLE02_SCREEN: 'Story_Product_Style02_Screen',
  SHOP_CLOTHING_SCREEN: 'Shop_Clothing_Screen',
  SHOP_CLOTHING_ON_SCROLL_SCREEN: 'Shop_Clothing_On_Scroll_Screen',
  CATEGORIES_FILTER_SCREEN: 'Categories_Filter_Screen',
  SEARCH_SCREEN: 'Search_Screen',
  SEARCH_RESULT_SCREEN: 'Search_Result_Screen',
  IMAGE_SEARCH_SCREEN: 'Image_Search_Screen',
  IMAGE_SEARCH_RESULTS: 'Image_Search_Results',
  FILTER_SCREEN: 'Filter_Screen',
  PRODUCT_SCREEN: 'Product_Screen',
  PRODUCT_SALE_SCREEN: 'Product_Sale_Screen',
  PRODUCT_FULL_SCREEN: 'Product_Full_Screen',
  PRODUCT_VARIATIONS_SCREEN: 'Product_Variations_Screen',
  REVIEWS_SCREEN:'Reviews_Screen',
  WISHLIST_SCREEN:'WishList_Screen',
  HOME_TAB: 'Home_Tab',
};
