export const RouteName = {
  START_SCREEN: 'StartScreen',
  CREATE_ACCOUNT_SCREEN: 'createAccountScreen',
  LOGIN_SCREEN: 'loginScreen',
  PASSWORD_SCREEN: 'passwordScreen',
  PASSWORD_TYPING_SCREEN: 'PasswordTypingScreen',
  WRONG_PASSWORD_SCREEN: 'WrongPasswordScreen',
  PASSWORD_RECOVERY_SCREEN: 'PasswordRecoveryScreen',
  PASSWORD_RECOVERY_CODE_SCREEN: 'PasswordRecoveryCodeScreen',
  NEW_PASSWORD_SCREEN: 'NewPasswordScreen',
  MAXIMUM_ATTEMPTS_SCREEN: 'MaximumAttemptsScreen',
  HELLO_CARD_SCREEN: 'HelloCardScreen',
  READY_CARD_SCREEN: 'ReadyCardScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  FULL_PROFILE_SCREEN: 'FullProfileScreen',
  SHOP_SCREEN: 'Shop-Screen',
  FLASH_SALE_LIVE_SCREEN: 'Flash_Sale_Live_Screen',
  FLASH_SALE_SCREEN: 'Flash_Sale_Screen',
  FLASH_SALE_FULL_SCREEN: 'Flash_Sale_Full_Screen',
  LIVE_SCREEN: 'Live_Screen',
  STORY_DOTS_SCREEN: 'Story_Dots_Screen',
  STORY_DOTS_TAB_SCREEN: 'Story_Dots_Tab_Screen',
  STORY_PRODUCT_STYLE01_SCREEN: 'Story_Product_Style01_Screen',
  STORY_BANNER_SCREEN: 'Story_Banner_Screen',
  STORY_PRODUCT_STYLE02_SCREEN: 'Story_Product_Style02_Screen',
  SHOP_CLOTHING_SCREEN: 'Shop_Clothing_Screen',
  SHOP_CLOTHING_ON_SCROLL_SCREEN: 'Shop_Clothing_On_Scroll_Screen',
  CATEGORIES_FILTER_SCREEN: 'Categories_Filter_Screen',
  SEARCH_SCREEN: 'Search_Screen',
  SEARCH_RESULT_SCREEN: 'Search_Result_Screen',
  IMAGE_SEARCH_SCREEN: 'Image_Search_Screen',
  IMAGE_SEARCH_RESULTS: 'Image_Search_Results',
  FILTER_SCREEN: 'Filter_Screen',
  PRODUCT_SCREEN: 'Product_Screen',
  PRODUCT_SALE_SCREEN: 'Product_Sale_Screen',
  PRODUCT_FULL_SCREEN: 'Product_Full_Screen',
  PRODUCT_VARIATIONS_SCREEN: 'Product_Variations_Screen',
  REVIEWS_SCREEN: 'Reviews_Screen',
  WISHLIST_SCREEN: 'WishList_Screen',
  WISHLIST_EMPTY_SCREEN: 'WishList_Empty_Screen',
  RECENTLY_VIEWED_SCREEN: 'Recently_Viewed_Screen',
  RECENTLY_VIEWED_DATE_CHOSEN_SCREEN: 'Recently_Viewed_Date_Chosen_Screen',
  RECENTLY_VIEWED_DATE_SCREEN: 'Recently_Viewed_Date_Screen',
  CART_SCREEN: 'Cart_Screen',
  CART_EMPTY_SHOWN_FROM_WISHLIST_SCREEN:
    'Cart_Empty_Shown_From_WishList_Screen',
  CART_EMPTY_SHOWN_FROM_POPULAR_SCREEN: 'Cart_Empty_Shown_From_Popular_Screen',
  PAYMENT_SCREEN: 'Payment_Screen',
  ADD_VOUCHER_SCREEN: 'Add_Voucher_Screen',
  VOUCHER_ADDED_SCREEN: 'Voucher_Added_Screen',
  EDIT_SHIPPING_ADDRESS_SCREEN: 'Edit_Shipping_Address_Screen',
  CHOOSE_PAYMENT_METHOD_1_CARD_SCREEN: 'Choose_Payment_Method_1_Card_Screen',
  CHOOSE_PAYMENT_METHOD_2_CARD_SCREEN: 'Choose_Payment_Method_2_Card_Screen',
  COULD_NOT_PROCEED_PAYMENT_SCREEN: 'Could_Not_Proceed_Payment_Screen',
  YOUR_CARD_BEEN_CHARGED_SCREEN: 'Your_Card_Been_Charged_Screen',
  PAYMENT_IN_PROGRESS_SCREEN: 'Payment_In_Progress_Screen',
  REVIEW_OPTION_SCREEN: 'Review_Option_Screen',
  PROFILE_TO_RECEIVE_NOTIFICATION_SCREEN:
    'Profile_To_Receive_Notification_Screen',
  TO_RECEIVE_SCREEN: 'To_Receive_Screen',
  TO_RECEIVE_PROGRESS_SCREEN: 'To_Receive_Progress_Screen',
  TO_RECEIVE_ATTEMPT_IS_NOT_SUCCESSFUL_SCREEN:
    'To_Receive_Attempt_Is_Not_Successful_Screen',
  DELIVERY_ATTEMPT_NOTIFICATION_SCREEN: 'Delivery_Attempt_Notification_Screen',
  DELIVERED_SCREEN: 'Delivered_Screen',
  MY_ACTIVITY_SCREEN: 'My_Activity_Screen',
  HISTORY_SCREEN: 'History_Screen',
  REVIEW_SCREEN: 'Review_Screen',
  REVIEW_DONE_SCREEN: 'Review_Done_Screen',
  CHAT_STARTING_QUESTION1: 'Chat_Starting_Question1',
  PROFILE_REWARD_SREEN: 'Profile_Reward_Screen',
  MY_VOUCHERS_SCREEN: 'My_Vouchers_Screen',
  REWARD_PROGRESS_SCREEN: 'Reward_Progress_Screen',
  PROFILE_VOUCHER_REMINDER_SCREEN: 'Profile_Voucher_Reminder_Screen',
  SETTINGS_SCREEN: 'Settings_Screen',
  SETTINGS_PROFILE_SCREEN: 'Settings_Profile_Screen',
  SETTINGS_ADD_CARD_SCREEN: 'Settings_Add_Card_Screen',
  PAYMENT_METHOD_HISTORY_SCREEN: 'Payment_Method_History_Screen',
  SHIPPING_ADDRESS_SCREEN: 'Shipping_Address_Screen',
  ABOUT_SCREEN: 'About_Screen',
  CHOOSE_YOUR_COUNTRY_SCREEN: 'Choose_Your_Country',
  CHOOSE_YOUR_LANGUAGE_SCREEN: 'Choose_Your_Language_Screen',
  CHOOSE_YOUR_CURRENCY_SCREEN: 'Choose_Your_Language_Currency_Screen',
  SIZES_TYPES_SCREEN:'Sizes_Types_Screen',
  HOME_TAB: 'Home_Tab',
};
